/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author oVTuan
 */
public class FindandReplace extends javax.swing.JFrame {

    Notepad mte;
    static int lastIndex;

    public FindandReplace(Notepad mte) {
        this.mte = mte;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        replaceLabel = new javax.swing.JLabel();
        replaceWith = new javax.swing.JTextField();
        findNextButton = new javax.swing.JButton();
        replaceButton = new javax.swing.JButton();
        replaceAllButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        matchCase = new javax.swing.JCheckBox();
        up = new javax.swing.JRadioButton();
        down = new javax.swing.JRadioButton();
        findWhat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Find what:");

        replaceLabel.setText("Repalce with:");

        findNextButton.setText("Find next");
        findNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNextButtonActionPerformed(evt);
            }
        });

        replaceButton.setText("Replace");
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });

        replaceAllButton.setText("Replace All");
        replaceAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceAllButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        matchCase.setText("Match Case");

        up.setText("up");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        down.setSelected(true);
        down.setText("down");
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchCase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchCase)
                    .addComponent(up)
                    .addComponent(down))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        findWhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findWhatActionPerformed(evt);
            }
        });
        findWhat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                findWhatKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(replaceLabel))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(replaceWith)
                            .addComponent(findWhat, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(replaceAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(replaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findNextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(findNextButton))
                    .addComponent(findWhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(replaceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(replaceAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replaceLabel)
                            .addComponent(replaceWith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNextButtonActionPerformed
        if (findWhat.getText().length() != 0) {
//            findNextButton.setEnabled(true);
            findNextWithSelection();
        } else {
            findNextButton.setEnabled(false);
        }
    }//GEN-LAST:event_findNextButtonActionPerformed

    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
        replaceNext();
    }//GEN-LAST:event_replaceButtonActionPerformed

    private void replaceAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceAllButtonActionPerformed

        int number = replaceAllNext();
        if (number == 0) {
            JOptionPane.showMessageDialog(null, "Total replacements made = " + replaceAllNext());
        } else {
            replaceAllNext();
        }
    }//GEN-LAST:event_replaceAllButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        up.setSelected(false);
    }//GEN-LAST:event_downActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        down.setSelected(false);
    }//GEN-LAST:event_upActionPerformed

    private void findWhatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findWhatKeyReleased
        enableDisableButtons();
    }//GEN-LAST:event_findWhatKeyReleased

    private void findWhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findWhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findWhatActionPerformed
    void enableDisableButtons() {
        if (findWhat.getText().length() == 0) {
            findNextButton.setEnabled(false);
            replaceButton.setEnabled(false);
            replaceAllButton.setEnabled(false);
        } else {
            findNextButton.setEnabled(true);
            replaceButton.setEnabled(true);
            replaceAllButton.setEnabled(true);
        }
    }

    int findNext() {
        String s1 = mte.getJtext().getText();
        String s2 = findWhat.getText();

        lastIndex = mte.getJtext().getCaretPosition();

        int selStart = mte.getJtext().getSelectionStart();
        int selEnd = mte.getJtext().getSelectionEnd();

        if (up.isSelected()) {
            if (selStart != selEnd) {
                lastIndex = selEnd - s2.length() - 1;
            }
            if (!matchCase.isSelected()) {
                lastIndex = s1.toUpperCase().lastIndexOf(s2.toUpperCase(), lastIndex);
            } else {
                lastIndex = s1.lastIndexOf(s2, lastIndex);
            }
        } else {
            if (selStart != selEnd) {
                lastIndex = selStart + 1;
            }
            if (!matchCase.isSelected()) {
                lastIndex = s1.toUpperCase().indexOf(s2.toUpperCase(), lastIndex);
            } else {
                lastIndex = s1.indexOf(s2, lastIndex);
            }
        }

        return lastIndex;
    }

    void findNextWithSelection() {

        int idx = findNext();
        if (idx != -1) {
            mte.getJtext().setSelectionStart(idx);
            mte.getJtext().setSelectionEnd(idx + findWhat.getText().length());
        } else {
            JOptionPane.showMessageDialog(this, "Cannot find" + " \"" + findWhat.getText() + "\"", "Find", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    void replaceNext() {
// if nothing is selectd
        if (mte.getJtext().getSelectionStart() == mte.getJtext().getSelectionEnd()) {
            findNextWithSelection();
            return;
        }
        String searchText = findWhat.getText();
        String temp = mte.getJtext().getSelectedText();    //get selected text

//check if the selected text matches the search text then do replacement
        if ((matchCase.isSelected() && temp.equals(searchText))
                || (!matchCase.isSelected() && temp.equalsIgnoreCase(searchText))) {
            mte.getJtext().replaceSelection(replaceWith.getText());
        }

        findNextWithSelection();
    }

    int replaceAllNext() {
        if (up.isSelected()) {
            mte.getJtext().setCaretPosition(mte.getJtext().getText().length() - 1);
        } else {
            mte.getJtext().setCaretPosition(0);
        }

        int idx = 0;
        int counter = 0;
        do {
            idx = findNext();
            if (idx == -1) {
                break;
            }
            counter++;
            mte.getJtext().replaceRange(replaceWith.getText(), idx, idx + findWhat.getText().length());
        } while (idx != -1);

        return counter;
    }

    void showDialog(Component parent, boolean isFind) {
        if (findWhat.getText().length() == 0) {
            findNextButton.setEnabled(false);
        } else {
            findNextButton.setEnabled(true);
        }

        replaceButton.setVisible(false);
        replaceAllButton.setVisible(false);
        replaceWith.setVisible(false);
        replaceLabel.setVisible(false);

        if (isFind) {
//card.show(buttonPanel,"find");
            this.setSize(460, 180);
            this.setTitle("Find");
        } else {
            replaceButton.setVisible(true);
            replaceAllButton.setVisible(true);
            replaceWith.setVisible(true);
            replaceLabel.setVisible(true);

//card.show(buttonPanel,"replace");
            this.setSize(450, 200);
            this.setTitle("Replace");
        }

        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton down;
    private javax.swing.JButton findNextButton;
    private javax.swing.JTextField findWhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox matchCase;
    private javax.swing.JButton replaceAllButton;
    private javax.swing.JButton replaceButton;
    private javax.swing.JLabel replaceLabel;
    private javax.swing.JTextField replaceWith;
    private javax.swing.JRadioButton up;
    // End of variables declaration//GEN-END:variables
}
